[package]
name = "aoc"
version = "0.1.0"
authors = ["Max McCarthy <hello@maxmcc.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.34"
indoc = "1.0.3"
itertools = "0.9.0"
lazy_static = "1.4.0"
parse-display = "0.4.0"
reformation = "0.5.3"
regex = "1.4.2"
